# Generated by Django 5.0.6 on 2024-06-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('age', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
