# Generated by Django 5.0.6 on 2024-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_age_galleryimage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
