# Generated by Django 5.0.6 on 2024-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.TextField(default='timezone.now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='topic',
            field=models.CharField(default='17.06.2024', max_length=100),
            preserve_default=False,
        ),
    ]
