# Generated by Django 5.0.6 on 2024-07-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='children_group',
            field=models.ManyToManyField(to='user.childrengroup'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='children_group',
            field=models.ManyToManyField(to='user.childrengroup'),
        ),
        migrations.DeleteModel(
            name='Childrens_group',
        ),
    ]
