# Generated by Django 5.0.6 on 2024-07-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_childrengroup_child_children_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='picture',
            field=models.ImageField(blank=True, upload_to='child_pictures'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(blank=True, upload_to='teacher_pictures'),
        ),
    ]
