# Generated by Django 5.0.6 on 2024-07-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_child_picture_alter_teacher_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
