# Generated by Django 5.0.6 on 2024-07-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_parent_alter_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrengroup',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
