# Generated by Django 5.0.6 on 2024-07-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_child_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='children_group',
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1),
        ),
        migrations.AddField(
            model_name='child',
            name='children_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.childrengroup'),
            preserve_default=False,
        ),
    ]
