# Generated by Django 5.0.6 on 2024-07-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_child_children_group_alter_child_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('can_view_admin_panel', 'Can view admin panel')]},
        ),
    ]
