# Generated by Django 5.0.6 on 2024-07-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childrengroup',
            options={'permissions': [('can_view_strawberry_group', 'Can view children group strawberry '), ('can_view_little_rascals_group', 'Can view children group little rascals ')]},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('can_view_admin_panel', 'Can view admin panel'), ('can_view_children_group', 'Can view children group')]},
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
